@rootURl = http://localhost:5223

GET {{rootURl}}/weatherforecast/
Accept: application/json

###
GET {{rootURl}}/api/task
Accept: application/json

###
GET {{rootURl}}/api/task/2
Accept:application/json

###
POST {{rootURl}}/api/task
Content-Type : application/json
{
  "Id" : 5,
  "Title" : "work",
  "IsDone" : true
}
